export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const SOCIAL_AUTH ="SOCIAL_AUTH";
export const LOGIN= "LOGIN";
export const PASSWORD_RESET= "PASSWORD_RESET";
export const NEW_PASSWORD="NEW_PASSWORD";
export const USER_NOT_FOUND="USER_NOT_FOUND";
export const REGISTER_USER= "REGISTER_USER";
const ACTION_TYPE = {
  NEW_ARTICLE: "NEW_ARTICLE",
  VIEW_ARTICLES: "VIEW_ARTICLES",
  PUBLISH_ARTICLE: "PUBLISH_ARTICLE"
};

export default ACTION_TYPE;
