export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const SOCIAL_AUTH = "SOCIAL_AUTH";
export const LOGIN = "LOGIN";
export const EMAIL_LOGIN = "EMAIL_LOGIN";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const NEW_PASSWORD = "NEW_PASSWORD";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const REGISTER_USER = "REGISTER_USER";

const ACTION_TYPE = {
  NEW_ARTICLE: "NEW_ARTICLE",
  VIEW_ARTICLES: "VIEW_ARTICLES",
  PUBLISH_ARTICLE: "PUBLISH_ARTICLE",
  VIEW_ONE_ARTICLE: "VIEW_ONE_ARTICLE",
  RATE_ARTICLE: "RATE_ARTICLE",
  ERROR: "ERROR",
  GET_PROFILE:"GET_PROFILE",
  EDIT_PROFILE:"EDIT_PROFILE",
  LIKE :"LIKE",
  DISLIKE : "DISLIKE",
  SHARE_ARTICLE:"SHARE_ARTICLE",
};
export const COMMENTS = {
  GET_COMMENTS: "GET_COMMENTS",
  POST_COMMENT: "POST_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  CREATE_THREAD: "CREATE_THREAD",
  LIKE_COMMENT:"LIKE_COMMENT"
};

export default ACTION_TYPE;
